import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import HeaderComponent from "./_components/Header-Component/headerComponent";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "800"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <HeaderComponent />
        {children}
      </body>
    </html>
  );
}
